
package com.stock.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.17
 * Sun Nov 15 12:53:34 UYST 2015
 * Generated source version: 2.7.17
 */

@XmlRootElement(name = "AnulacionDeReserva", namespace = "http://stock.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnulacionDeReserva", namespace = "http://stock.com/")

public class AnulacionDeReserva {

    @XmlElement(name = "arg0")
    private long arg0;

    public long getArg0() {
        return this.arg0;
    }

    public void setArg0(long newArg0)  {
        this.arg0 = newArg0;
    }

}

