
package com.stock.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.17
 * Sun Nov 15 12:53:33 UYST 2015
 * Generated source version: 2.7.17
 */

@XmlRootElement(name = "ReservaDeProductos", namespace = "http://stock.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservaDeProductos", namespace = "http://stock.com/")

public class ReservaDeProductos {

    @XmlElement(name = "arg0")
    private java.util.List<com.stock.Pedido> arg0;

    public java.util.List<com.stock.Pedido> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.List<com.stock.Pedido> newArg0)  {
        this.arg0 = newArg0;
    }

}

