
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.client.stock;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:06:23.454-02:00
 * Generated source version: 2.7.17
 * 
 */

@javax.jws.WebService(
                      serviceName = "StockService",
                      portName = "StockPort",
                      targetNamespace = "http://stock.com/",
                      wsdlLocation = "http://localhost:8090/soap-esb/Stock?wsdl",
                      endpointInterface = "com.client.stock.Stock")
                      
public class StockImpl implements Stock {

    private static final Logger LOG = Logger.getLogger(StockImpl.class.getName());

    /* (non-Javadoc)
     * @see com.client.stock.Stock#anulacionDeReserva(long  arg0 )*
     */
    public com.client.stock.ResultadoAnulacion anulacionDeReserva(long arg0) { 
        LOG.info("Executing operation anulacionDeReserva");
        System.out.println(arg0);
        try {
            com.client.stock.ResultadoAnulacion _return = new com.client.stock.ResultadoAnulacion();
            _return.setCodigo("Codigo1148015499");
            _return.setDescripcion("Descripcion1951278032");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.client.stock.Stock#reservaDeProductos(java.util.List<com.client.stock.Pedido>  arg0 )*
     */
    public com.client.stock.ResultadoPedido reservaDeProductos(java.util.List<com.client.stock.Pedido> arg0) { 
        LOG.info("Executing operation reservaDeProductos");
        System.out.println(arg0);
        try {
            com.client.stock.ResultadoPedido _return = new com.client.stock.ResultadoPedido();
            _return.setCodigo("Codigo1235775640");
            _return.setDescripcion("Descripcion-1075294358");
            _return.setIdReserva(3565467424286749907l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
