package com.client.stock;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:06:23.468-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://stock.com/", name = "Stock")
@XmlSeeAlso({ObjectFactory.class})
public interface Stock {

    @WebMethod(operationName = "AnulacionDeReserva", action = "urn:AnulacionDeReserva")
    @RequestWrapper(localName = "AnulacionDeReserva", targetNamespace = "http://stock.com/", className = "com.client.stock.AnulacionDeReserva")
    @ResponseWrapper(localName = "AnulacionDeReservaResponse", targetNamespace = "http://stock.com/", className = "com.client.stock.AnulacionDeReservaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.client.stock.ResultadoAnulacion anulacionDeReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebMethod(operationName = "ReservaDeProductos", action = "urn:ReservaDeProductos")
    @RequestWrapper(localName = "ReservaDeProductos", targetNamespace = "http://stock.com/", className = "com.client.stock.ReservaDeProductos")
    @ResponseWrapper(localName = "ReservaDeProductosResponse", targetNamespace = "http://stock.com/", className = "com.client.stock.ReservaDeProductosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.client.stock.ResultadoPedido reservaDeProductos(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.client.stock.Pedido> arg0
    );
}
