package com.client.epuerto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:54:54.904-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://com/", name = "IAmazoniaEPuerto")
@XmlSeeAlso({ObjectFactory.class})
public interface IAmazoniaEPuerto {

    @WebMethod
    @RequestWrapper(localName = "confirmarOrden", targetNamespace = "http://com/", className = "com.client.epuerto.ConfirmarOrden")
    @ResponseWrapper(localName = "confirmarOrdenResponse", targetNamespace = "http://com/", className = "com.client.epuerto.ConfirmarOrdenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.client.epuerto.EPuertoResponse confirmarOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        com.client.epuerto.EPuertoConfirmacionRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "recibirPedido", targetNamespace = "http://com/", className = "com.client.epuerto.RecibirPedido")
    @ResponseWrapper(localName = "recibirPedidoResponse", targetNamespace = "http://com/", className = "com.client.epuerto.RecibirPedidoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.client.epuerto.EPuertoResponse recibirPedido(
        @WebParam(name = "arg0", targetNamespace = "")
        com.client.epuerto.EPuertoPedidoRequest arg0
    );
}
