
package com.client.epuerto;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:54:54.823-02:00
 * Generated source version: 2.7.17
 * 
 */
public final class IAmazoniaEPuerto_IAmazoniaEPuertoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/", "IAmazoniaEPuertoService");

    private IAmazoniaEPuerto_IAmazoniaEPuertoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IAmazoniaEPuertoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IAmazoniaEPuertoService ss = new IAmazoniaEPuertoService(wsdlURL, SERVICE_NAME);
        IAmazoniaEPuerto port = ss.getIAmazoniaEPuertoPort();  
        
        {
        System.out.println("Invoking confirmarOrden...");
        com.client.epuerto.EPuertoConfirmacionRequest _confirmarOrden_arg0 = new com.client.epuerto.EPuertoConfirmacionRequest();
        _confirmarOrden_arg0.setCodigoResultado(-1273513815);
        _confirmarOrden_arg0.setDescripcion("Descripcion1052456236");
        _confirmarOrden_arg0.setIdCompra("IdCompra1982940407");
        _confirmarOrden_arg0.setIdReserva("IdReserva-1563811713");
        com.client.epuerto.EPuertoResponse _confirmarOrden__return = port.confirmarOrden(_confirmarOrden_arg0);
        System.out.println("confirmarOrden.result=" + _confirmarOrden__return);


        }
        {
        System.out.println("Invoking recibirPedido...");
        com.client.epuerto.EPuertoPedidoRequest _recibirPedido_arg0 = new com.client.epuerto.EPuertoPedidoRequest();
        _recibirPedido_arg0.setCantidad(603470513);
        _recibirPedido_arg0.setIdCompra("IdCompra1056517339");
        _recibirPedido_arg0.setIdProducto(-828337197089843230l);
        com.client.epuerto.EPuertoResponse _recibirPedido__return = port.recibirPedido(_recibirPedido_arg0);
        System.out.println("recibirPedido.result=" + _recibirPedido__return);


        }

        System.exit(0);
    }

}
