package com.client.epuerto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:54:54.913-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "IAmazoniaEPuertoService", 
                  wsdlLocation = "http://localhost:8090/soap-esb/EPuerto?wsdl",
                  targetNamespace = "http://com/") 
public class IAmazoniaEPuertoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com/", "IAmazoniaEPuertoService");
    public final static QName IAmazoniaEPuertoPort = new QName("http://com/", "IAmazoniaEPuertoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/soap-esb/EPuerto?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IAmazoniaEPuertoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/soap-esb/EPuerto?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IAmazoniaEPuertoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IAmazoniaEPuertoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IAmazoniaEPuertoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaEPuertoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaEPuertoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaEPuertoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IAmazoniaEPuerto
     */
    @WebEndpoint(name = "IAmazoniaEPuertoPort")
    public IAmazoniaEPuerto getIAmazoniaEPuertoPort() {
        return super.getPort(IAmazoniaEPuertoPort, IAmazoniaEPuerto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAmazoniaEPuerto
     */
    @WebEndpoint(name = "IAmazoniaEPuertoPort")
    public IAmazoniaEPuerto getIAmazoniaEPuertoPort(WebServiceFeature... features) {
        return super.getPort(IAmazoniaEPuertoPort, IAmazoniaEPuerto.class, features);
    }

}
