
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.client.epuerto;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T13:54:54.891-02:00
 * Generated source version: 2.7.17
 * 
 */

@javax.jws.WebService(
                      serviceName = "IAmazoniaEPuertoService",
                      portName = "IAmazoniaEPuertoPort",
                      targetNamespace = "http://com/",
                      wsdlLocation = "http://localhost:8090/soap-esb/EPuerto?wsdl",
                      endpointInterface = "com.client.epuerto.IAmazoniaEPuerto")
                      
public class IAmazoniaEPuertoImpl implements IAmazoniaEPuerto {

    private static final Logger LOG = Logger.getLogger(IAmazoniaEPuertoImpl.class.getName());

    /* (non-Javadoc)
     * @see com.client.epuerto.IAmazoniaEPuerto#confirmarOrden(com.client.epuerto.EPuertoConfirmacionRequest  arg0 )*
     */
    public com.client.epuerto.EPuertoResponse confirmarOrden(com.client.epuerto.EPuertoConfirmacionRequest arg0) { 
        LOG.info("Executing operation confirmarOrden");
        System.out.println(arg0);
        try {
            com.client.epuerto.EPuertoResponse _return = new com.client.epuerto.EPuertoResponse();
            _return.setMensaje("Mensaje901951239");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.client.epuerto.IAmazoniaEPuerto#recibirPedido(com.client.epuerto.EPuertoPedidoRequest  arg0 )*
     */
    public com.client.epuerto.EPuertoResponse recibirPedido(com.client.epuerto.EPuertoPedidoRequest arg0) { 
        LOG.info("Executing operation recibirPedido");
        System.out.println(arg0);
        try {
            com.client.epuerto.EPuertoResponse _return = new com.client.epuerto.EPuertoResponse();
            _return.setMensaje("Mensaje-1993218486");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
