
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.17
 * Sun Nov 15 18:15:31 UYST 2015
 * Generated source version: 2.7.17
 */

@XmlRootElement(name = "recepcionOrdenes", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recepcionOrdenes", namespace = "http://com/")

public class RecepcionOrdenes {

    @XmlElement(name = "arg0")
    private com.DataOrden arg0;

    public com.DataOrden getArg0() {
        return this.arg0;
    }

    public void setArg0(com.DataOrden newArg0)  {
        this.arg0 = newArg0;
    }

}

