
package com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.17
 * Sun Nov 01 18:35:47 UYST 2015
 * Generated source version: 2.7.17
 */

@XmlRootElement(name = "recibirOrdenCompra", namespace = "http://com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirOrdenCompra", namespace = "http://com/", propOrder = {"idCompra", "nroTarjeta", "productos"})

public class RecibirOrdenCompra {

    @XmlElement(name = "idCompra")
    private java.lang.String idCompra;
    @XmlElement(name = "nroTarjeta")
    private long nroTarjeta;
    @XmlElement(name = "productos")
    private java.util.List<com.DataProducto> productos;

    public java.lang.String getIdCompra() {
        return this.idCompra;
    }

    public void setIdCompra(java.lang.String newIdCompra)  {
        this.idCompra = newIdCompra;
    }

    public long getNroTarjeta() {
        return this.nroTarjeta;
    }

    public void setNroTarjeta(long newNroTarjeta)  {
        this.nroTarjeta = newNroTarjeta;
    }

    public java.util.List<com.DataProducto> getProductos() {
        return this.productos;
    }

    public void setProductos(java.util.List<com.DataProducto> newProductos)  {
        this.productos = newProductos;
    }

}

