package com.client.pagosya;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T17:56:35.003-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebServiceClient(name = "IAmazoniaPagosYaService", 
                  wsdlLocation = "http://localhost:8090/soap-esb/PagosYa?wsdl",
                  targetNamespace = "http://com/") 
public class IAmazoniaPagosYaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com/", "IAmazoniaPagosYaService");
    public final static QName IAmazoniaPagosYaPort = new QName("http://com/", "IAmazoniaPagosYaPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/soap-esb/PagosYa?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IAmazoniaPagosYaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/soap-esb/PagosYa?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IAmazoniaPagosYaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IAmazoniaPagosYaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IAmazoniaPagosYaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaPagosYaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaPagosYaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAmazoniaPagosYaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IAmazoniaPagosYa
     */
    @WebEndpoint(name = "IAmazoniaPagosYaPort")
    public IAmazoniaPagosYa getIAmazoniaPagosYaPort() {
        return super.getPort(IAmazoniaPagosYaPort, IAmazoniaPagosYa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAmazoniaPagosYa
     */
    @WebEndpoint(name = "IAmazoniaPagosYaPort")
    public IAmazoniaPagosYa getIAmazoniaPagosYaPort(WebServiceFeature... features) {
        return super.getPort(IAmazoniaPagosYaPort, IAmazoniaPagosYa.class, features);
    }

}
