
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.client.pagosya;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T17:56:34.986-02:00
 * Generated source version: 2.7.17
 * 
 */

@javax.jws.WebService(
                      serviceName = "IAmazoniaPagosYaService",
                      portName = "IAmazoniaPagosYaPort",
                      targetNamespace = "http://com/",
                      wsdlLocation = "http://localhost:8090/soap-esb/PagosYa?wsdl",
                      endpointInterface = "com.client.pagosya.IAmazoniaPagosYa")
                      
public class IAmazoniaPagosYaImpl implements IAmazoniaPagosYa {

    private static final Logger LOG = Logger.getLogger(IAmazoniaPagosYaImpl.class.getName());

    /* (non-Javadoc)
     * @see com.client.pagosya.IAmazoniaPagosYa#realizarPago(com.client.pagosya.PagosYaRequest  pagosYaRequest )*
     */
    public com.client.pagosya.PagosYaResponse realizarPago(com.client.pagosya.PagosYaRequest pagosYaRequest) { 
        LOG.info("Executing operation realizarPago");
        System.out.println(pagosYaRequest);
        try {
            com.client.pagosya.PagosYaResponse _return = new com.client.pagosya.PagosYaResponse();
            _return.setIdPago(5296392207738297999l);
            _return.setMensaje("Mensaje1466479458");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
