package com.client.pagosya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T17:56:34.995-02:00
 * Generated source version: 2.7.17
 * 
 */
@WebService(targetNamespace = "http://com/", name = "IAmazoniaPagosYa")
@XmlSeeAlso({ObjectFactory.class})
public interface IAmazoniaPagosYa {

    @WebMethod
    @RequestWrapper(localName = "realizarPago", targetNamespace = "http://com/", className = "com.client.pagosya.RealizarPago")
    @ResponseWrapper(localName = "realizarPagoResponse", targetNamespace = "http://com/", className = "com.client.pagosya.RealizarPagoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.client.pagosya.PagosYaResponse realizarPago(
        @WebParam(name = "PagosYaRequest", targetNamespace = "")
        com.client.pagosya.PagosYaRequest pagosYaRequest
    );
}
