
package com.client.pagosya;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-11-15T17:56:34.934-02:00
 * Generated source version: 2.7.17
 * 
 */
public final class IAmazoniaPagosYa_IAmazoniaPagosYaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/", "IAmazoniaPagosYaService");

    private IAmazoniaPagosYa_IAmazoniaPagosYaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IAmazoniaPagosYaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IAmazoniaPagosYaService ss = new IAmazoniaPagosYaService(wsdlURL, SERVICE_NAME);
        IAmazoniaPagosYa port = ss.getIAmazoniaPagosYaPort();  
        
        {
        System.out.println("Invoking realizarPago...");
        com.client.pagosya.PagosYaRequest _realizarPago_pagosYaRequest = new com.client.pagosya.PagosYaRequest();
        _realizarPago_pagosYaRequest.setFechaHora("FechaHora-1106489047");
        _realizarPago_pagosYaRequest.setIdCompra(-3392763087250333362l);
        _realizarPago_pagosYaRequest.setMonto(0.6052425472949409);
        _realizarPago_pagosYaRequest.setNroTarjeta("NroTarjeta-1414174477");
        com.client.pagosya.PagosYaResponse _realizarPago__return = port.realizarPago(_realizarPago_pagosYaRequest);
        System.out.println("realizarPago.result=" + _realizarPago__return);


        }

        System.exit(0);
    }

}
